# bundle exec jekyll serve

title: Manufacturing & Engineering Co-op
email: jnb_mec@gmail.com
location: 5011 Granville Ave, Richmond, BC # aka. Burnett's adress
phone: +1 123-123-1234 # Temp random. Or Mr. Bevan's phone number?
description: >-
  Insert description here..........

# Temp using my account; use domain name later.
baseurl: "/mecoop"
url: "https://akixuu.github.io"
social_links:
  linkedin: https://www.linkedin.com/company/jnb-mec/
  instagram: https://www.instagram.com/_mec24/

theme: null # By default, Jekyll uses Minima

plugins:
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-sass-converter

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "wrapper"

sass:
  style: compressed

include:
  - _sass/vendor/_rfs.scss

  
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
